application: python-blog-rb
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /login
  script: login.app  
    
- url: /logout
  script: logout.app

- url: /signup
  script: signup.app

- url: /([0-9]+)(?:\.json)?
  script: post.app  

- url: /newpost
  script: new_post.app
  
- url: /welcome
  script: welcome.app

- url: .*/(?:\.json)?
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
